language: dart
sudo: required
dart:
  - dev
  - stable
dart_task:
  - test: --platform vm
  - test: --platform chrome
  - dartanalyzer
matrix:
  include:
    - dart: stable
      after_success: ./tool/coverage.sh
  include:
    - dart: stable
      dart_task: dartfmt
cache:
  directories:
    - $HOME/.pub-cache