name: xml
version: 5.1.0

description: A lightweight library for parsing, traversing, querying, transforming and building XML documents.
homepage: https://github.com/renggli/dart-xml

environment:
  sdk: '>=2.12.0-0 <3.0.0'
dependencies:
  collection: ^1.15.0
  meta: ^1.3.0
  petitparser: ^4.1.0
dependency_overrides:
  petitparser:
    path: ../PetitParser/petitparser
dev_dependencies:
  args: ^2.0.0
  test: ^1.16.0
