name: xml
version: 2.1.0
author: Lukas Renggli <renggli@gmail.com>
description: A lightweight library for parsing, traversing, and querying XML documents.
homepage: http://github.com/renggli/dart-xml
environment:
  sdk: '>=1.0.0 <2.0.0'
documentation: http://jenkins.lukas-renggli.ch/job/dart-xml/javadoc
dependencies:
  petitparser: '>=1.0.0 <2.0.0'
dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  unittest: '>=0.10.0 <0.12.0'
  junitconfiguration: '>=1.0.0 <2.0.0'
