name: xml
version: 2.0.0
author: Lukas Renggli <renggli@gmail.com>
description: A simple, small and fast XML library for Dart.
homepage: https://github.com/renggli/PetitXmlDart
environment:
  sdk: '>=1.0.0 <2.0.0'
documentation: http://jenkins.lukas-renggli.ch/job/PetitXmlDart/javadoc
dependencies:
  petitparser: '>=1.0.0 <2.0.0'
dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  unittest: '>=0.10.0 <0.11.0'
  junitconfiguration: '>=1.0.0 <2.0.0'
