name: xml
version: 2.2.2-dev
author: Lukas Renggli <renggli@gmail.com>
description: A lightweight library for parsing, traversing, querying and building XML documents.
homepage: https://github.com/renggli/dart-xml
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  petitparser: '>=1.3.0 <2.0.0'
dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  unittest: '>=0.11.0 <0.12.0'
  junitconfiguration: '>=1.0.0 <2.0.0'
