name: xml
version: 3.2.0

author: Lukas Renggli <renggli@gmail.com>
description: A lightweight library for parsing, traversing, querying, transforming and building XML documents.
homepage: https://github.com/renggli/dart-xml

environment:
  sdk: ">=2.0.0-dev.69 <3.0.0"
dependencies:
  petitparser: ^2.0.0
  collection: ^1.14.0
dev_dependencies:
  build_runner: ^0.9.0
  build_test: ^0.10.0
  build_web_compilers: ^0.4.0
  test: ^1.3.0
